# Gemfile
source "https://rubygems.org"

ruby "3.4.8"

gem "rails", "~> 7.1.0"
gem "pg", "~> 1.5"
gem "puma", "~> 6.4"
gem "tzinfo-data", platforms: [:windows, :jruby]
gem "bootsnap", require: false

# API
gem "jsonapi-serializer", "~> 2.2"
gem "rack-cors", "~> 2.0"
gem "kaminari", "~> 1.2"
gem "bcrypt", "~> 3.1"
gem "image_processing", "~> 1.12"

group :development, :test do
  gem "debug"
  gem "rspec-rails", "~> 6.1"
  gem "factory_bot_rails", "~> 6.4"
  gem "faker", "~> 3.2"
end